name: Bicep Module Consume

on:
  push:
    paths:
      - 3-consume/**.bicep
      - 3-consume/**.parameters.json
      - .github/workflows/bicep-consume.yml
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  consume:
    environment: Azure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Azure Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACR_PULL_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Bicep modules
        run: .github/build-modules.ps1 -ModulesPath ./3-consume/
        shell: pwsh

      - name: Deploy Container Apps
        if: github.event == 'workflow_dispatch' || github.ref_name == 'main'
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: bicep-workload-demo
          template: 3-consume/main.bicep

      - name: Print Container Apps URL
        if: github.event == 'workflow_dispatch' || github.ref_name == 'main'
        run: echo ${{ steps.deploy.outputs.url }}
