name: Bicep Module Publish

on:
  push:
    tags:
      - "v*"
    branches:
      - main
    paths:
      - 2-publish/**.bicep
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    if: (startsWith(github.ref, 'refs/tags/v') || github.event == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get repo with tags

      - name: "Azure Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACR_PUSH_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Bicep modules
        run: .github/build-modules.ps1
        shell: pwsh
