name: Bicep Module Publish

on:
  push:
    tags:
      - "*"
    branches:
      - main
    paths:
      - 2-publish/**.bicep
      - .github/workflows/bicep-publish.yml
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish. Must be a valid git tag.'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    environment: Azure-Push
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get repo with tags

      - name: "Azure Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACR_PUSH_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Bicep modules
        run: .github/build-modules.ps1 -ModulesPath ./2-publish/
        shell: pwsh

      - name: Publish Bicep modules (push)
        if: github.event_name == 'push'
        run: .github/publish-modules.ps1 -ModulesPath ./2-publish -AddLatest
        shell: pwsh

      - name: Publish Bicep modules (dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: .github/publish-modules.ps1 -ModulesPath ./2-publish -Version ${{ inputs.version }}
        shell: pwsh