name: Bicep Module Build

on:
  push:
    paths:
      - "**.bicep"
    branches-ignore:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    environment: Azure
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      - name: "Azure Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACR_PULL_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Bicep modules
        run: .github/build-modules.ps1 -ModulesPath ./
        shell: pwsh
